const applicationsElement = document.querySelector("#applications");
const titleElement = document.querySelector("#portal-title");
const subtitleElement = document.querySelector("#portal-subtitle");
const noticeElement = document.querySelector("#notice");
const generatedAtElement = document.querySelector("#generated-at");

function text(value, fallback = "") {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function formatGeneratedAt(value) {
  if (!value) {
    return "Generated by Workbench";
  }

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return `Generated ${value}`;
  }

  return `Generated ${new Intl.DateTimeFormat(undefined, {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  }).format(date)}`;
}

function node(tag, className, content) {
  const element = document.createElement(tag);
  if (className) {
    element.className = className;
  }
  if (content !== undefined && content !== null) {
    element.textContent = String(content);
  }
  return element;
}

function credentialNode(credential) {
  const wrapper = node("div", "credential");
  wrapper.appendChild(node("span", null, text(credential.label, "Credential")));

  const username = node("code", null, `Username: ${text(credential.username, "n/a")}`);
  const password = node("code", null, `Password: ${text(credential.password, "n/a")}`);
  wrapper.append(username, password);
  return wrapper;
}

function technologyFallbackText(technology) {
  const explicitText = text(technology.logoText);
  if (explicitText) {
    return explicitText;
  }

  const name = text(technology.name, "?");
  const words = name.split(/[^a-z0-9]+/i).filter(Boolean);
  if (words.length > 1) {
    return words.map((word) => word.charAt(0)).join("").slice(0, 4).toUpperCase();
  }

  return name.slice(0, 4).toUpperCase();
}

function technologyLogoTemplate(id) {
  switch (id) {
    case "angularjs":
      return '<svg viewBox="0 0 48 48" focusable="false"><path d="M24 4 7 10l3 25 14 9 14-9 3-25L24 4z" fill="currentColor"/><text x="24" y="29" text-anchor="middle" fill="#fff" font-size="22" font-weight="900">A</text></svg>';
    case "react":
      return '<svg viewBox="0 0 48 48" focusable="false" fill="none" stroke="currentColor" stroke-width="3"><ellipse cx="24" cy="24" rx="18" ry="7"/><ellipse cx="24" cy="24" rx="18" ry="7" transform="rotate(60 24 24)"/><ellipse cx="24" cy="24" rx="18" ry="7" transform="rotate(120 24 24)"/><circle cx="24" cy="24" r="3.5" fill="currentColor" stroke="none"/></svg>';
    case "php":
      return '<svg viewBox="0 0 48 48" focusable="false"><ellipse cx="24" cy="24" rx="20" ry="13" fill="currentColor"/><text x="24" y="28" text-anchor="middle" fill="#fff" font-size="13" font-weight="900">PHP</text></svg>';
    case "dotnet":
      return '<svg viewBox="0 0 48 48" focusable="false"><rect x="7" y="8" width="34" height="32" rx="8" fill="currentColor"/><text x="24" y="28" text-anchor="middle" fill="#fff" font-size="12" font-weight="900">.NET</text></svg>';
    case "mariadb":
      return '<svg viewBox="0 0 48 48" focusable="false" fill="none" stroke="currentColor" stroke-width="3"><ellipse cx="24" cy="13" rx="16" ry="7"/><path d="M8 13v21c0 4 7 8 16 8s16-4 16-8V13"/><path d="M8 24c0 4 7 8 16 8s16-4 16-8" opacity=".45"/><text x="24" y="27" text-anchor="middle" fill="currentColor" stroke="none" font-size="9" font-weight="900">MDB</text></svg>';
    case "postgresql":
      return '<svg viewBox="0 0 48 48" focusable="false" fill="none" stroke="currentColor" stroke-width="3"><ellipse cx="24" cy="13" rx="16" ry="7"/><path d="M8 13v21c0 4 7 8 16 8s16-4 16-8V13"/><path d="M8 24c0 4 7 8 16 8s16-4 16-8" opacity=".45"/><text x="24" y="28" text-anchor="middle" fill="currentColor" stroke="none" font-size="12" font-weight="900">PG</text></svg>';
    default:
      return "";
  }
}

function technologyNode(technology) {
  const wrapper = node("div", "tech-item");
  const color = text(technology.color);
  if (color) {
    wrapper.style.setProperty("--tech-color", color);
  }

  const logo = node("span", "tech-logo");
  logo.setAttribute("aria-hidden", "true");

  const inlineLogo = technologyLogoTemplate(text(technology.id).toLowerCase());
  if (inlineLogo) {
    logo.insertAdjacentHTML("beforeend", inlineLogo);
    logo.classList.add("has-graphic");
  } else if (text(technology.logoUrl)) {
    const image = document.createElement("img");
    image.src = text(technology.logoUrl);
    image.alt = "";
    image.loading = "lazy";
    image.addEventListener("error", () => logo.classList.remove("has-graphic"));
    image.addEventListener("load", () => logo.classList.add("has-graphic"));
    logo.appendChild(image);
  }

  logo.appendChild(node("span", "tech-logo-fallback", technologyFallbackText(technology)));

  const textGroup = node("span", "tech-text");
  textGroup.appendChild(node("small", null, text(technology.label, "Stack")));
  textGroup.appendChild(node("strong", null, text(technology.name, "Technology")));

  wrapper.append(logo, textGroup);
  return wrapper;
}

function techStackNode(technologies) {
  const items = Array.isArray(technologies) ? technologies.filter((technology) => text(technology?.name)) : [];
  if (!items.length) {
    return null;
  }

  const wrapper = node("section", "tech-stack");
  wrapper.setAttribute("aria-label", "Technology stack");
  wrapper.appendChild(node("div", "tech-stack-title", "Technology stack"));
  const grid = node("div", "tech-stack-grid");
  items.forEach((technology) => grid.appendChild(technologyNode(technology)));
  wrapper.appendChild(grid);
  return wrapper;
}

function entryNode(entry) {
  const wrapper = node("article", "entry");
  const header = node("div", "entry-header");
  const labelGroup = node("div");
  labelGroup.appendChild(node("strong", null, text(entry.label, "Entry point")));
  labelGroup.appendChild(node("small", null, text(entry.role, "Demo role")));

  const status = node("span", entry.url ? "status-pill" : "status-pill unavailable", entry.url ? "Available" : "Waiting for URL");
  header.append(labelGroup, status);
  wrapper.appendChild(header);

  const note = text(entry.note);
  if (note) {
    wrapper.appendChild(node("p", "entry-note", note));
  }

  const credentials = Array.isArray(entry.credentials) ? entry.credentials : [];
  if (credentials.length) {
    const credentialList = node("div", "credential-list");
    credentials.forEach((credential) => credentialList.appendChild(credentialNode(credential)));
    wrapper.appendChild(credentialList);
  }

  const link = node("a", entry.url ? "open-link" : "open-link disabled", entry.url ? `Open ${text(entry.label, "site")}` : "URL unavailable");
  if (entry.url) {
    link.href = entry.url;
    link.target = "_blank";
    link.rel = "noreferrer";
  }
  wrapper.appendChild(link);

  return wrapper;
}

function applicationNode(application) {
  const wrapper = node("article", "app-card");
  const header = node("div", "app-card-header");
  const titleGroup = node("div");
  titleGroup.appendChild(node("span", "version-label", text(application.versionLabel, "Demo")));
  titleGroup.appendChild(node("h2", null, text(application.name, "OpenEMR Demo")));
  header.append(titleGroup, node("span", "status-pill", text(application.statusLabel, "Demo")));
  wrapper.appendChild(header);

  const summary = text(application.summary);
  if (summary) {
    wrapper.appendChild(node("p", "summary", summary));
  }

  const tags = Array.isArray(application.tags) ? application.tags.filter(Boolean) : [];
  if (tags.length) {
    const tagRow = node("div", "tag-row");
    tags.forEach((tag) => tagRow.appendChild(node("span", "tag", tag)));
    wrapper.appendChild(tagRow);
  }

  const techStack = techStackNode(application.techStack);
  if (techStack) {
    wrapper.appendChild(techStack);
  }

  const entryList = node("div", "entry-list");
  const entries = Array.isArray(application.entryPoints) ? application.entryPoints : [];
  entries.forEach((entry) => entryList.appendChild(entryNode(entry)));
  wrapper.appendChild(entryList);

  return wrapper;
}

async function loadPortal() {
  try {
    const response = await fetch("./demo-portal-data.json", { cache: "no-store" });
    if (!response.ok) {
      throw new Error(`Portal data returned HTTP ${response.status}`);
    }
    const data = await response.json();
    titleElement.textContent = text(data.title, "OpenEMR Demo Portal");
    subtitleElement.textContent = text(data.subtitle, "Choose an available demo application.");
    generatedAtElement.textContent = formatGeneratedAt(data.generatedAt);

    const notice = text(data.notice);
    if (notice) {
      noticeElement.textContent = notice;
      noticeElement.hidden = false;
    }

    applicationsElement.replaceChildren();
    const applications = Array.isArray(data.applications) ? data.applications : [];
    if (!applications.length) {
      applicationsElement.appendChild(node("div", "empty", "No demo applications have been published yet."));
      return;
    }

    applications.forEach((application) => applicationsElement.appendChild(applicationNode(application)));
  } catch (error) {
    generatedAtElement.textContent = "Portal data unavailable";
    applicationsElement.replaceChildren(node("div", "empty", error instanceof Error ? error.message : String(error)));
  }
}

void loadPortal();
