namespace OpenEmr.Modernized.Api.Models;

public sealed record AppointmentSearchResponse(
    string DatasetId,
    string DatasetVersion,
    string? PatientId,
    string? FromDate,
    int Limit,
    int TotalMatches,
    IReadOnlyList<AppointmentListItem> Appointments);

public sealed record AppointmentListItem(
    string Id,
    string SeriesRootId,
    bool IsRecurringSeries,
    bool IsVirtualOccurrence,
    int? OccurrenceNumber,
    string PatientId,
    int LegacyPid,
    string Pubpid,
    string PatientDisplayName,
    string Date,
    string StartTime,
    int DurationMinutes,
    string Title,
    string? Status,
    string? Room,
    int? CategoryId,
    string? CategoryName,
    int? ProviderId,
    string? ProviderName,
    int? FacilityId,
    string? FacilityName,
    int? BillingLocationId,
    string? BillingLocationName,
    string? Comments,
    int RecurrenceType,
    int? RepeatFrequency,
    int? RepeatUnit,
    int? RepeatOnNum,
    int? RepeatOnDay,
    int? RepeatOnFrequency,
    IReadOnlyList<int> RecurrenceDays,
    string? RecurrenceEndDate,
    IReadOnlyList<string> RecurrenceExdates,
    int RecurrenceExceptionCount,
    string RecurrenceLabel,
    int ProviderOverlapCount,
    IReadOnlyList<string> ProviderOverlapAppointmentIds,
    int PatientOverlapCount,
    IReadOnlyList<string> PatientOverlapAppointmentIds,
    int RoomOverlapCount,
    IReadOnlyList<string> RoomOverlapAppointmentIds,
    bool ReminderDue,
    string ReminderStatus,
    string ReminderChannel,
    string? ReminderContact,
    int? ReminderLeadDays,
    int? ConvertedEncounterId,
    string? ConvertedEncounterDate,
    int ConvertedBillingLineCount);

public sealed record AppointmentDetail(
    string Id,
    string SeriesRootId,
    bool IsRecurringSeries,
    bool IsVirtualOccurrence,
    int? OccurrenceNumber,
    string PatientId,
    int LegacyPid,
    string Pubpid,
    string PatientDisplayName,
    string FirstName,
    string LastName,
    string? Sex,
    string DateOfBirth,
    string Date,
    string StartTime,
    int DurationMinutes,
    string Title,
    string? Status,
    string? Room,
    int? CategoryId,
    string? CategoryName,
    int? ProviderId,
    string? ProviderName,
    int? FacilityId,
    string? FacilityName,
    int? BillingLocationId,
    string? BillingLocationName,
    string? Comments,
    int RecurrenceType,
    int? RepeatFrequency,
    int? RepeatUnit,
    int? RepeatOnNum,
    int? RepeatOnDay,
    int? RepeatOnFrequency,
    IReadOnlyList<int> RecurrenceDays,
    string? RecurrenceEndDate,
    IReadOnlyList<string> RecurrenceExdates,
    int RecurrenceExceptionCount,
    string RecurrenceLabel,
    string? PatientPurpose,
    int ProviderOverlapCount,
    IReadOnlyList<string> ProviderOverlapAppointmentIds,
    int PatientOverlapCount,
    IReadOnlyList<string> PatientOverlapAppointmentIds,
    int RoomOverlapCount,
    IReadOnlyList<string> RoomOverlapAppointmentIds,
    bool ReminderDue,
    string ReminderStatus,
    string ReminderChannel,
    string? ReminderContact,
    int? ReminderLeadDays,
    int? ConvertedEncounterId,
    string? ConvertedEncounterDate,
    int ConvertedBillingLineCount);

public sealed record AppointmentCreateRequest(
    string PatientId,
    int? ProviderId,
    string Title,
    string Date,
    string StartTime,
    int DurationMinutes,
    int? FacilityId,
    int? BillingLocationId,
    int? CategoryId,
    string? Room,
    string? Comments,
    int? RecurrenceType,
    int? RepeatFrequency,
    int? RepeatUnit,
    int? RepeatOnNum,
    int? RepeatOnDay,
    int? RepeatOnFrequency,
    IReadOnlyList<int>? RecurrenceDays,
    string? RecurrenceEndDate,
    IReadOnlyList<string>? RecurrenceExdates,
    bool EnforceConflictPolicy = false);

public sealed record AppointmentAvailabilityValidationRequest(
    string PatientId,
    int? ProviderId,
    string Date,
    string StartTime,
    int DurationMinutes,
    int? FacilityId,
    string? Room,
    string? ExcludeAppointmentId);

public sealed record AppointmentAvailabilityValidationResponse(
    bool Available,
    string ValidationStatus,
    string Date,
    string StartTime,
    string EndTime,
    int DurationMinutes,
    bool PatientKnown,
    int? ProviderId,
    string? ProviderName,
    bool ProviderAvailable,
    int? FacilityId,
    string? FacilityName,
    bool FacilityAvailable,
    bool WithinBusinessHours,
    int ConflictCount,
    IReadOnlyList<AppointmentAvailabilityConflict> Conflicts,
    IReadOnlyList<string> Messages);

public sealed record AppointmentAvailabilityConflict(
    string AppointmentId,
    string ConflictType,
    string PatientId,
    string PatientDisplayName,
    string Date,
    string StartTime,
    string EndTime,
    string Title);

public sealed record AppointmentWaitlistResponse(
    string DatasetId,
    string DatasetVersion,
    string AsOfDate,
    int TotalWaiting,
    IReadOnlyList<AppointmentWaitlistItem> Items);

public sealed record AppointmentWaitlistItem(
    string AppointmentId,
    string PatientId,
    int LegacyPid,
    string Pubpid,
    string PatientDisplayName,
    string Date,
    string StartTime,
    string EndTime,
    int DurationMinutes,
    string Title,
    string? Status,
    int? CategoryId,
    string? CategoryName,
    int? ProviderId,
    string? ProviderName,
    int? FacilityId,
    string? FacilityName,
    string? Room,
    string? Reason,
    int DaysUntilRequestedSlot,
    string Priority,
    bool ReminderCreated,
    string? ReminderId,
    string? ReminderStatus,
    string? ReminderAssignedTo,
    string? ReminderBody);

public sealed record AppointmentReminderDispatchResponse(
    string DatasetId,
    string DatasetVersion,
    string AsOfDate,
    string AppointmentId,
    string DispatchId,
    string AuditId,
    string DispatchedAt,
    string PatientId,
    int LegacyPid,
    string Pubpid,
    string PatientDisplayName,
    string AppointmentDate,
    string StartTime,
    string EndTime,
    string Title,
    string ReminderStatus,
    string ReminderChannel,
    string? ReminderContact,
    int? ReminderLeadDays,
    string QueueName,
    string DispatchStatus,
    string ExternalReference,
    string TemplateName,
    string MessagePreview);

public sealed record AppointmentReminderDispatchHistoryResponse(
    string DatasetId,
    string DatasetVersion,
    string AsOfDate,
    int EventCount,
    IReadOnlyList<AppointmentReminderDispatchResponse> Entries);

public sealed record AppointmentUpdateRequest(
    int? ProviderId,
    string Title,
    string Date,
    string StartTime,
    int DurationMinutes,
    int? FacilityId,
    int? BillingLocationId,
    int? CategoryId,
    string? Room,
    string? Status,
    string? Comments,
    int? RecurrenceType,
    int? RepeatFrequency,
    int? RepeatUnit,
    int? RepeatOnNum,
    int? RepeatOnDay,
    int? RepeatOnFrequency,
    IReadOnlyList<int>? RecurrenceDays,
    string? RecurrenceEndDate,
    IReadOnlyList<string>? RecurrenceExdates);

public sealed record AppointmentOccurrenceRescheduleRequest(
    int? ProviderId,
    string Title,
    string Date,
    string StartTime,
    int DurationMinutes,
    int? FacilityId,
    int? BillingLocationId,
    int? CategoryId,
    string? Room,
    string? Status,
    string? Comments);

public sealed record AppointmentStatusUpdateRequest(
    string Status,
    string? Title);
