param(
    [ValidateSet("legacy-openemr", "modernized-openemr")]
    [string] $Target = "legacy-openemr",

    [ValidateSet(
        "all",
        "database",
        "http",
        "ui",
        "workflow",
        "slice1",
        "scheduling",
        "encounters",
        "clinical-lists",
        "messages",
        "documents",
        "encounter-documents",
        "encounter-document-revision",
        "encounter-billing",
        "encounter-claims",
        "encounter-procedures",
        "encounter-diagnoses",
        "document-content",
        "document-preview",
        "document-revision",
        "insurance",
        "immunizations",
        "procedures",
        "procedure-pending-orders",
        "billing",
        "claims",
        "payments",
        "account-balance",
        "account-aging",
        "account-ledger",
        "account-statement",
        "account-statement-generation",
        "account-statement-pdf",
        "account-statement-batch",
        "account-statement-batch-package",
        "account-collections-work-queue",
        "account-collections-follow-up",
        "admin",
        "reports",
        "reports-export",
        "admin-access-control",
        "workflow-contact",
        "workflow-demographics",
        "workflow-registration",
        "workflow-appointments",
        "workflow-appointment-reschedule",
        "workflow-appointment-arrival",
        "workflow-appointment-checkout",
        "workflow-appointment-noshow",
        "workflow-appointment-category",
        "workflow-appointment-pending",
        "workflow-appointment-provider",
        "workflow-appointment-facility",
        "workflow-appointment-billing-location",
        "workflow-appointment-comments",
        "workflow-appointment-recurrence",
        "workflow-appointment-series",
        "workflow-appointment-recurrence-exceptions",
        "workflow-appointment-occurrence-cancel",
        "workflow-appointment-occurrence-restore",
        "workflow-appointment-occurrence-reschedule",
        "workflow-appointment-recurrence-exception-edit",
        "workflow-appointment-series-root-update",
        "workflow-appointment-series-root-metadata",
        "workflow-appointment-monthly-recurrence",
        "workflow-appointment-recurrence-unit-matrix",
        "workflow-appointment-days-of-week-recurrence",
        "workflow-appointment-monthly-repeat-on-recurrence",
        "workflow-appointment-series-recurrence-update",
        "workflow-appointment-provider-overlap",
        "workflow-appointment-patient-overlap",
        "workflow-appointment-room-overlap",
        "workflow-appointment-reminders",
        "workflow-encounters",
        "workflow-encounter-metadata",
        "workflow-encounter-billing",
        "workflow-encounter-diagnoses",
        "workflow-encounter-fee-sheet",
        "workflow-encounter-procedures",
        "workflow-encounter-procedure-results",
        "workflow-encounter-signoff",
        "workflow-encounter-cosignature",
        "workflow-encounter-amendment-history",
        "workflow-encounter-documents",
        "workflow-encounter-binary-documents",
        "workflow-encounter-document-scanned-attachment",
        "workflow-encounter-document-signoff",
        "workflow-encounter-document-denial",
        "workflow-encounter-document-metadata",
        "workflow-encounter-document-move",
        "workflow-encounter-document-content-replace",
        "workflow-encounter-document-binary-content-replace",
        "workflow-encounter-document-revision-replace",
        "workflow-encounter-document-archive",
        "workflow-encounter-document-lifecycle",
        "workflow-encounter-document-external-link",
        "workflow-clinical-lists",
        "workflow-problems",
        "workflow-medications",
        "workflow-messages",
        "workflow-message-assignment",
        "workflow-message-content",
        "workflow-message-reply",
        "workflow-message-update-metadata",
        "workflow-documents",
        "workflow-document-binary",
        "workflow-document-binary-content-replace",
        "workflow-document-image-preview",
        "workflow-document-image-thumbnail",
        "workflow-document-pdf-preview",
        "workflow-document-lifecycle",
        "workflow-document-scanned-attachment",
        "workflow-document-signoff",
        "workflow-document-external-link",
        "workflow-document-denial",
        "workflow-document-metadata",
        "workflow-document-archive",
        "workflow-document-content-replace",
        "workflow-document-revision-replace",
        "workflow-insurance",
        "workflow-insurance-subscriber",
        "workflow-prescriptions",
        "workflow-immunizations",
        "workflow-billing",
        "workflow-billing-diagnosis",
        "workflow-billing-correction",
        "workflow-billing-modifier",
        "workflow-payment-posting",
        "workflow-claims",
        "workflow-patient-payments",
        "workflow-procedures",
        "workflow-procedure-result-correction",
        "workflow-procedure-specimen",
        "workflow-procedure-specimen-detail",
        "workflow-procedure-order-correction",
        "workflow-procedure-report-correction",
        "workflow-procedure-report-signoff",
        "workflow-procedure-report-bulk-signoff",
        "workflow-procedure-report-reopen-review",
        "workflow-procedure-report-review-queue",
        "workflow-procedure-report-review-queue-filters",
        "workflow-procedure-report-review-queue-provider-filters",
        "workflow-procedure-report-review-queue-lab-filters",
        "workflow-procedure-order-catalog",
        "workflow-procedure-order-catalog-lifecycle",
        "workflow-procedure-vendor-compendium-import",
        "workflow-procedure-order-queue",
        "workflow-procedure-order-transmit",
        "workflow-procedure-lab-provider-catalog",
        "workflow-procedure-lab-provider-directory",
        "workflow-procedure-lab-provider-lifecycle",
        "workflow-procedure-lab-provider-configuration",
        "workflow-procedure-lab-provider-address-book",
        "workflow-admin",
        "workflow-admin-users",
        "workflow-admin-access",
        "workflow-admin-memberships",
        "workflow-admin-login",
        "workflow-admin-login-audit",
        "workflow-admin-session",
        "workflow-admin-audit-protection",
        "workflow-admin-directory-protection",
        "workflow-admin-authorization-policy",
        "workflow-reports-protection",
        "workflow-reports-authorization-policy",
        "workflow-clinical-list-authorization-policy",
        "workflow-patient-protection",
        "workflow-patient-authorization-policy",
        "workflow-patient-mutation-authorization-policy",
        "workflow-patient-duplicate-detection",
        "workflow-patient-registration-validation",
        "workflow-patient-deceased-status",
        "workflow-patient-guardian-contact",
        "workflow-patient-guardian-details",
        "workflow-patient-social-details",
        "workflow-patient-employer-core",
        "workflow-patient-provider-assignment",
        "workflow-patient-care-team",
        "workflow-patient-care-team-members",
        "workflow-patient-care-team-contact",
        "patient-history",
        "patient-portal-account",
        "workflow-patient-portal-reset",
        "workflow-patient-portal-access",
        "workflow-patient-portal-authentication",
        "workflow-patient-portal-session",
        "workflow-patient-portal-home",
        "workflow-patient-portal-messages",
        "workflow-patient-portal-compose",
        "workflow-patient-portal-reply",
        "workflow-patient-portal-thread",
        "workflow-patient-portal-delete",
        "workflow-patient-portal-read",
        "workflow-patient-portal-batch-archive",
        "workflow-patient-portal-all-messages",
        "workflow-patient-portal-documents",
        "workflow-patient-portal-appointments",
        "workflow-patient-portal-appointment-request",
        "workflow-patient-portal-appointment-options",
        "workflow-patient-portal-clinical-summary",
        "workflow-patient-portal-lab-results",
        "workflow-patient-portal-medical-report",
        "workflow-patient-portal-generated-medical-report",
        "workflow-patient-portal-medical-report-pdf",
        "workflow-patient-portal-report-issues",
        "workflow-patient-portal-report-forms",
        "workflow-patient-portal-report-template",
        "workflow-patient-portal-report-package",
        "workflow-patient-portal-report-audit",
        "workflow-patient-portal-message-audit",
        "workflow-patient-portal-message-encryption",
        "workflow-patient-portal-message-forward",
        "workflow-patient-portal-deleted-messages",
        "workflow-patient-portal-report-procedures",
        "workflow-patient-portal-report-procedure-artifacts",
        "workflow-patient-portal-home-immunizations",
        "workflow-patient-portal-profile",
        "workflow-patient-portal-profile-change-request",
        "workflow-clinical-list-protection",
        "workflow-appointment-protection",
        "workflow-appointment-authorization-policy",
        "workflow-appointment-mutation-authorization-policy",
        "workflow-encounter-protection",
        "workflow-encounter-authorization-policy",
        "workflow-encounter-mutation-authorization-policy",
        "workflow-document-protection",
        "workflow-document-authorization-policy",
        "workflow-document-mutation-authorization-policy",
        "workflow-message-protection",
        "workflow-message-authorization-policy",
        "workflow-message-mutation-authorization-policy",
        "workflow-billing-authorization-policy",
        "workflow-billing-mutation-authorization-policy",
        "workflow-billing-protection",
        "workflow-procedure-authorization-policy",
        "workflow-procedure-mutation-authorization-policy",
        "workflow-procedure-protection"
    )]
    [string] $Suite = "all",

    [string] $Plan = "",

    [ValidateSet("none", "run", "suite", "test")]
    [string] $Reset = "run",

    [switch] $Headed,

    [string] $Grep = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$parityRoot = Join-Path $repoRoot "parity-tests"

if (-not (Test-Path (Join-Path $parityRoot "package.json"))) {
    throw "Missing parity test project at $parityRoot."
}

Push-Location $parityRoot
try {
    $arguments = @(
        "tsx",
        "src/cli/run-tests.ts",
        "--target", $Target
    )

    if ($Plan) {
        $arguments += @("--plan", $Plan)
    } else {
        $arguments += @("--suite", $Suite)
    }

    if ($Reset) {
        $arguments += @("--reset", $Reset)
    }

    if ($Headed) {
        $arguments += "--headed"
    }

    if ($Grep) {
        $arguments += @("--grep", $Grep)
    }

    & npx @arguments
    exit $LASTEXITCODE
} finally {
    Pop-Location
}
