@OpenEmr.Modernized.Api_HostAddress = http://localhost:5001

GET {{OpenEmr.Modernized.Api_HostAddress}}/health
Accept: application/json

###

GET {{OpenEmr.Modernized.Api_HostAddress}}/api/patients?search=MOD-PAT-0001&limit=5
Accept: application/json

###

GET {{OpenEmr.Modernized.Api_HostAddress}}/api/patients/MOD-PAT-0001
Accept: application/json

###
