INSERT INTO patient_data (
  `uuid`,
  `title`,
  `language`,
  `fname`,
  `lname`,
  `DOB`,
  `street`,
  `postal_code`,
  `city`,
  `state`,
  `country_code`,
  `ss`,
  `occupation`,
  `phone_home`,
  `phone_contact`,
  `phone_cell`,
  `status`,
  `date`,
  `sex`,
  `providerID`,
  `email`,
  `ethnicity`,
  `family_size`,
  `monthly_income`,
  `homeless`,
  `financial_review`,
  `pubpid`,
  `pid`,
  `hipaa_mail`,
  `hipaa_voice`,
  `hipaa_notice`,
  `hipaa_message`,
  `hipaa_allowsms`,
  `hipaa_allowemail`,
  `allow_patient_portal`,
  `cmsportal_login`,
  `created_by`,
  `updated_by`,
  `mothersname`,
  `guardiansname`,
  `guardianrelationship`,
  `guardianphone`,
  `guardianemail`,
  `guardiansex`,
  `guardianaddress`,
  `guardiancity`,
  `guardianstate`,
  `guardianpostalcode`,
  `guardiancountry`,
  `guardianworkphone`
) VALUES (
  UNHEX('dcfe280b3c0333f731f30f6aa967b90d'),
  'Mr.',
  'english',
  'Nora',
  'Kim',
  '2002-05-05',
  '104 Test Patient Avenue',
  '91950',
  'National City',
  'CA',
  'US',
  '103-13-1003',
  'Food Service Manager',
  '(619) 555-1004',
  '(619) 555-1004',
  '(619) 555-1004',
  'single',
  '2024-01-04 09:00:00',
  'Male',
  1,
  'mod-pat-0004@example.test',
  'Not Hispanic or Latino',
  5,
  2600,
  'NO',
  '2026-01-01',
  'MOD-PAT-0004',
  100004,
  'YES',
  'YES',
  'YES',
  'YES',
  'YES',
  'YES',
  'YES',
  'mod-pat-0004@example.test',
  1,
  1,
  'Avery Kim',
  'Jordan Kim',
  'care_giver',
  '(619) 555-3004',
  'jordan.kim@example.test',
  'Female',
  '204 Guardian Lane',
  'National City',
  'CA',
  '91950',
  'USA',
  '(619) 555-4004'
)
ON DUPLICATE KEY UPDATE
  `uuid` = VALUES(`uuid`),
  `fname` = VALUES(`fname`),
  `lname` = VALUES(`lname`),
  `DOB` = VALUES(`DOB`),
  `email` = VALUES(`email`),
  `allow_patient_portal` = VALUES(`allow_patient_portal`),
  `cmsportal_login` = VALUES(`cmsportal_login`);

INSERT INTO patient_access_onsite (
  `pid`,
  `portal_username`,
  `portal_pwd`,
  `portal_pwd_status`,
  `portal_login_username`,
  `portal_onetime`
) VALUES (
  100004,
  'mod-pat-0004@example.test',
  '$2y$12$rVnICT6EtKZGpK5482QqFOfD5bZhBAUNRLsneTJvhGSwEj3bEcnMq',
  1,
  'mod-pat-0004@example.test',
  ''
)
ON DUPLICATE KEY UPDATE
  `portal_username` = VALUES(`portal_username`),
  `portal_pwd` = VALUES(`portal_pwd`),
  `portal_pwd_status` = VALUES(`portal_pwd_status`),
  `portal_login_username` = VALUES(`portal_login_username`),
  `portal_onetime` = VALUES(`portal_onetime`);
